version: 2

before:
  hooks:
    - go mod download
builds:
  - main: main.go
    binary: boring-registry
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    ldflags:
      - -s
      - -w
      - -X github.com/boring-registry/boring-registry/version.Version={{.Env.INTERNAL_VERSION}}
      - -X github.com/boring-registry/boring-registry/version.Commit={{.Commit}}
      - -X github.com/boring-registry/boring-registry/version.Date={{.Date}}

dockers:
  - image_templates:
      - "{{ .Env.ECR_REGISTRY }}/docker/prod/{{ .Env.IMAGE_REPOSITORY }}:{{ .Env.INTERNAL_VERSION }}-amd64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Env.INTERNAL_VERSION}}"
      - "--label=org.opencontainers.image.source=https://github.com/confluentinc/boring-registry"
  - image_templates:
      - "{{ .Env.ECR_REGISTRY }}/docker/prod/{{ .Env.IMAGE_REPOSITORY }}:{{ .Env.INTERNAL_VERSION }}-arm64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Env.INTERNAL_VERSION}}"
      - "--label=org.opencontainers.image.source=https://github.com/confluentinc/boring-registry"
    goarch: arm64

docker_manifests:
  - name_template: "{{ .Env.ECR_REGISTRY }}/docker/prod/{{ .Env.IMAGE_REPOSITORY }}:{{ .Env.INTERNAL_VERSION }}"
    image_templates:
      - "{{ .Env.ECR_REGISTRY }}/docker/prod/{{ .Env.IMAGE_REPOSITORY }}:{{ .Env.INTERNAL_VERSION }}-amd64"
      - "{{ .Env.ECR_REGISTRY }}/docker/prod/{{ .Env.IMAGE_REPOSITORY }}:{{ .Env.INTERNAL_VERSION }}-arm64"

release:
  disable: true

checksum:
  disable: true

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
