version: 2

before:
  hooks:
    - go mod download
builds:
  - main: main.go
    binary: boring-registry
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    ldflags:
      - -s
      - -w
      - -X github.com/boring-registry/boring-registry/version.Version={{.Env.INTERNAL_VERSION}}
      - -X github.com/boring-registry/boring-registry/version.Commit={{.Commit}}
      - -X github.com/boring-registry/boring-registry/version.Date={{.Date}}

dockers_v2:
  - image:
      - "{{ .Env.ECR_REGISTRY }}/docker/prod/{{ .Env.IMAGE_REPOSITORY }}"
    dockerfile: Dockerfile
    tags:
      - "{{ .Env.INTERNAL_VERSION }}"
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.title": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Env.INTERNAL_VERSION}}"
      "org.opencontainers.image.source": "https://github.com/confluentinc/boring-registry"

release:
  disable: true

checksum:
  disable: true

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

